# Generated by Django 4.2.2 on 2023-07-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ads_brand_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='', max_length=500),
        ),
    ]
